name: Delete-PAF-Data-On-Perm-Ban-LiteBans
version: ${project.version}
main: de.simonsator.partyandfriends.datadeleter.litebans.LBDeleterPlugin
author: Simonsator
depends: ['PartyAndFriends', 'LiteBans']
api-version: 1.13